---
# This playbook is to workaround a docker bug found in https://bugzilla.redhat.com/show_bug.cgi?id=1671861
- hosts: all
  gather_facts: yes
  tasks:

    - name: Download docker rpms
	  get_url:
        url: http://download.eng.bos.redhat.com/brewroot/vol/rhel-7/packages/docker/1.13.1/93.gitb2f74b2.el7/x86_64/{{ item }}
        dest: ~/{{ item }}
      with-items:
        - docker-1.13.1-93.gitb2f74b2.el7.x86_64.rpm   
	- docker-client-1.13.1-93.gitb2f74b2.el7.x86_64.rpm 
	- docker-common-1.13.1-93.gitb2f74b2.el7.x86_64.rpm  
	- docker-rhel-push-plugin-1.13.1-93.gitb2f74b2.el7.x86_64.rpm
	
	- name: Install docker rpms
	  shell: rpm -ivh --force {{ item }}
	  sudo: true
	  with-items:
	    - docker-rhel-push-plugin-1.13.1-93.gitb2f74b2.el7.x86_64.rpm   
	    - docker-common-1.13.1-93.gitb2f74b2.el7.x86_64.rpm   
	    - docker-client-1.13.1-93.gitb2f74b2.el7.x86_64.rpm   
	    - docker-1.13.1-93.gitb2f74b2.el7.x86_64.rpm   
	 
    - name: Restart Docker service
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
